[package]
name = "example"
version = "0.1.0"
authors = ["Alex Pikalov <alex.pikalov.khar@gmail.com>", "Kamil Rojewski <kamil.rojewski@gmail.com>"]

[dependencies]
time = "0.1.36"
cdrs_tokio_helpers_derive = { path = ".." }
cdrs = "2.3.2"
